# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MEGHNA RAJAMOHAN — DIGITAL GARDEN
email: meghna.rajamohan@gmail.com
description: Welcome to my digital garden. This is a space for my projects and musings to grow during as I continue my journey through the world of design.
  
baseurl: 
url: 
author: 

# Layout
excerpt_separator: "<!--more-->"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

sass:
  style: compressed

collections:
  notes:
    output: true
    permalink: /:slug

feed:
  path: feed.xml
  collections:
    notes:
      path: "/feed.xml"
    posts:
      path: ""

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"


permalink: pretty
relative_permalinks: false
use_html_extension: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _includes/notes_graph.json
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
